name: Publish to NPM when missing
author: geoblink
description: Automatically publish current version to NPM if not already published

runs:
  using: docker
  image: Dockerfile

branding:
  icon: package
  color: gray-dark
